---
title: "Publications"
---

### Journal Articles

-   

### Policy Papers

-   Jakkrit Kuanpoth, et al. 2022. “Reviewing Trade Competition Act B.E. 2560.” \[In Thai.\] paper submitted to the Trade Competition Commission of Thailand.

-   Phakphum Jatupitpornchan, et al. 2021. “Redesigning Thailand’s Social Protection System: Leaving No One Behind.” *TDRI Quarterly Review* ,Vol.36, No.4.

-   Somchai Jitsuchon, et al. 2021. “Designing Social Security System to Support Future Labor Market.” \[In Thai.\] paper submitted to Office of the National Economic and Social Development Council.

-   Somchai Jitsuchon, et al. 2021. “Monitor and Evaluate 12th National Plan Under the Strategy for Creating a Just Society and Reduce Inequality.” \[In Thai.\] paper submitted to Office of the National Economic and Social Development Council.

-   Somchai Jitsuchon, et al. 2021. “Evaluation of Social Impacts from Covid-19.” \[In Thai.\] paper submitted to Thailand Science Research and Innovation.

-   Somchai Jitsuchon, et al. 2021. “Effective Measures to Promote Financial Planning of the Thai Population for a Longevity Society.” \[In Thai.\] paper submitted to National Research Council of Thailand.

-   Somchai Jitsuchon, et al. 2021. “Inclusive Social Policy and Child-sensitive Social Protection Phase II.” paper submitted to UNICEF Thailand.

### Newspaper Articles/Blogs

-   [Disability benefits system needs revamp](https://www.bangkokpost.com/opinion/opinion/2340557/disability-benefits-system-needs-revamp)\
    *Bangkok Post*, July 2022

-   [‘คนพิการที่ตกหล่น’ ด้วยวิธีการประเมินของไทย](https://www.bangkokbiznews.com/columnist/1002528)\
    *Krungthep Turakij*, May 2022

-   [TDRI: เราควรเรียนรู้อะไรจากการจัดซื้อวัคซีนของต่างประเทศ](https://prachatai.com/journal/2021/07/94215)\
    *Prachatai*, July 2021

-   ['ลอตเตอรี่' การออมของคนจน?](https://www.bangkokbiznews.com/news/detail/933972)\
    *Krungthep Turakij*, April 2021

-   [Lottery solution for old-age security](https://www.bangkokpost.com/opinion/opinion/2121651/lottery-solution-for-old-age-security)\
    *Bangkok Post*, May 2021

-   [“ลอตเตอรี่” โอกาสหรืออุปสรรคต่อการออมของคนจน?](https://tdri.or.th/2021/04/lottery-the-expected-utility/)\
    *TDRI*, April 2021

-   [การจัดการความเหลื่อมล้ำจากวิกฤตโควิด](https://tdri.or.th/2020/10/inequalities-in-the-time-of-covid-19/)\
    *TDRI*, October 2020
